enchantment-table:
    mode: flat-rate
    items:
        EMERALD: 3
        DIAMOND: 1
enchantment-command:
    mode: flat-rate
    items:
        EMERALD: 5
        DIAMOND: 3
messages:
    success: '&aSuccessfully enchanted &9%enchanted-item% &ausing:'
    failure: '&cFailed to enchant &9%enchanted-item%&c, it requires:'
    show-items: true
    item-format: '&9%payment-amount% x %payment-item%'