name: ItemEnchanting
author: Lucariatias
version: 2.1.3
main: me.lucariatias.plugins.itemenchanting.ItemEnchanting
description: Changes enchanting mechanics to use items rather than experience
commands:
    itemenchant:
        description: Enchants the item in your hand using items
        usage: /<command> [enchantment] [level]
permissions:
    itemenchanting.command.itemenchant: 
        description: Allows usage of /itemenchant
        default: op
    itemenchanting.unsafe:
        description: Allows unsafe enchants with /itemenchant
        default: op