enchantment-table:
    mode: flat-rate
    items:
        EMERALD:
            amount: 3
            data: 0
        DIAMOND:
            amount: 1
            data: 0
enchantment-command:
    mode: multiply
    items:
        EMERALD:
            amount: 5
            data: 0
        DIAMOND:
            amount: 3
            data: 0
messages:
    success: '&aSuccessfully enchanted &9%enchanted-item% &ausing:'
    failure: '&cFailed to enchant &9%enchanted-item%&c, it requires:'
    show-items: true
    item-format: '&9%payment-amount% x %payment-item%'