name: ${project.name}
author: Lucariatias
version: ${project.version}
main: io.github.lucariatias.itemenchanting.ItemEnchanting
description: ${project.description}
commands:
    itemenchant:
        description: Enchants the item in your hand using items
        usage: /<command> [enchantment] [level]
permissions:
    itemenchanting.command.itemenchant: 
        description: Allows usage of /itemenchant
        default: op
    itemenchanting.unsafe:
        description: Allows unsafe enchants with /itemenchant
        default: op